name: Build and Release AppImage

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Run on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3.x

      - name: Create virtual environment
        run: |
          python -m venv ocr_env
          source ocr_env/bin/activate
          pip install --upgrade pip

      - name: Install Torch and Torchvision
        run: |
          source ocr_env/bin/activate
          echo "torch>=2.0.0" > requirements_torch.txt
          echo "torchvision>=0.15.0" >> requirements_torch.txt
          pip install -r requirements_torch.txt

      - name: Install remaining dependencies
        run: |
          source ocr_env/bin/activate
          # Create a temporary requirements file excluding flash-attn
          grep -v "flash-attn" requirements.txt > requirements_no_flash_attn.txt
          pip install -r requirements_no_flash_attn.txt

      - name: Install PyInstaller
        run: |
          source ocr_env/bin/activate
          pip install pyinstaller

      - name: Build AppImage
        run: |
          chmod +x build_appimage.sh
          ./build_appimage.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nanonets-OCR-AppImage
          path: appimage_build/Nanonets_OCR_GUI-x86_64.AppImage

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: Nanonets-OCR-AppImage

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Nanonets_OCR_GUI-x86_64.AppImage
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
