name: Build and Release AppImage

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Run on tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3.x

      - name: Install CUDA Toolkit 12.6
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-6
          echo "CUDA_HOME=/usr/local/cuda-12.6" >> $GITHUB_ENV
          echo "/usr/local/cuda-12.6/bin" >> $GITHUB_PATH

      - name: Install Torch and Torchvision
        run: |
          echo "torch>=2.0.0" > requirements_torch.txt
          echo "torchvision>=0.15.0" >> requirements_torch.txt
          pip install -r requirements_torch.txt

      - name: Install Flash-Attn (without build isolation)
        run: pip install flash-attn>=2.5.8 --no-build-isolation

      - name: Install remaining dependencies
        run: |
          # Create a temporary requirements file excluding flash-attn
          grep -v "flash-attn" requirements.txt > requirements_no_flash_attn.txt
          pip install -r requirements_no_flash_attn.txt

      - name: Build AppImage
        run: |
          chmod +x appimage_build/build_appimage.sh
          ./appimage_build/build_appimage.sh

      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nanonets-OCR-AppImage
          path: appimage_build/Nanonets_OCR_GUI-x86_64.AppImage

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: Nanonets-OCR-AppImage

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Nanonets_OCR_GUI-x86_64.AppImage
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
